# Generated by Django 3.1.7 on 2021-03-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Диспетчер', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Состояние заявки', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Торговая точка, адрес', max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Сервисный инженер', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория неисправности', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(help_text='ФИО инициатора заявки', max_length=64)),
                ('rec_num', models.CharField(help_text='Номер заявки', max_length=12)),
                ('description', models.TextField(help_text='Содержание заявки', max_length=1000)),
                ('sign', models.DateTimeField(blank=True, help_text='Дата и время передачи заявки инженеру', null=True)),
                ('visit', models.DateField(blank=True, help_text='Дата визита инженера', null=True)),
                ('result', models.TextField(blank=True, help_text='Результат выезда', max_length=1000, null=True)),
                ('form', models.TextField(blank=True, help_text='Номер заказа-наряда', max_length=10, null=True)),
                ('staff', models.ForeignKey(help_text='Диспетчер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
                ('status', models.ForeignKey(help_text='Состояние заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status')),
                ('store', models.ForeignKey(help_text='Торговая точка, адрес', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.store')),
                ('tech', models.ForeignKey(blank=True, help_text='Сервисный инженер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tech')),
                ('trouble', models.ForeignKey(help_text='Категория неисправности', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trouble')),
            ],
        ),
    ]
