# Generated by Django 3.1.7 on 2021-03-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Диспетчер', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Состояние заявки', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Торговая точка, адрес', max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Сервисный инженер', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория неисправности', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.DateField(auto_now_add=True)),
                ('rec_time', models.TimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=100, verbose_name='ФИО инициатора заявки')),
                ('rec_num', models.CharField(max_length=12, verbose_name='Номер заявки')),
                ('description', models.TextField(max_length=1000, verbose_name='Содержание заявки')),
                ('sign', models.DateTimeField(blank=True, verbose_name='Дата и время передачи заявки инженеру')),
                ('visit', models.DateField(blank=True, null=True, verbose_name='Дата визита инженера')),
                ('result', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Результат выезда')),
                ('form', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер заказа-наряда')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff', verbose_name='Диспетчер')),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status', verbose_name='Статус заявки')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.store', verbose_name='Торговая точка, адрес')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tech', verbose_name='Сервисный инженер')),
                ('trouble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trouble', verbose_name='Категория неисправности')),
            ],
            options={
                'ordering': ['-rec_date'],
            },
        ),
    ]
