# Generated by Django 3.1.7 on 2021-03-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='sign',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи заявки инженеру'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='tech',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tech', verbose_name='Сервисный инженер'),
        ),
    ]
