# Generated by Django 3.1.7 on 2021-03-20 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210319_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='rec_datetime',
        ),
        migrations.AddField(
            model_name='rec',
            name='rec_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec',
            name='rec_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
