# Generated by Django 3.1.7 on 2021-03-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210320_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_date']},
        ),
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.ForeignKey(default='Принята', help_text='Статус заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status'),
        ),
    ]
