# Generated by Django 3.1.7 on 2021-03-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210322_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.ForeignKey(default=0, help_text='Статус заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status'),
        ),
    ]
