# Generated by Django 3.1.7 on 2021-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210324_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_time']},
        ),
        migrations.AlterField(
            model_name='rec',
            name='jpg',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Скан-копия заказа-наряда'),
        ),
    ]
