# Generated by Django 3.1.7 on 2021-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210324_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='jpg',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Скан-копия заказа-наряда'),
        ),
    ]
