# Generated by Django 3.1.7 on 2021-03-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210324_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_time'], 'permissions': (('can_add_and_update', 'Возможность создавать и обновлять  заявки'),)},
        ),
    ]
