# Generated by Django 3.1.7 on 2021-03-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210322_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='customer',
            field=models.CharField(max_length=64, verbose_name='ФИО инициатора заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Содержание заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='form',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Номер заказа-наряда'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec_num',
            field=models.IntegerField(max_length=12, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Результат выезда'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='sign',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время передачи заявки инженеру'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff', verbose_name='Диспетчер'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status', verbose_name='Состояние заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.store', verbose_name='Торговая точка, адрес'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tech', verbose_name='Сервисный инженер'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='trouble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trouble', verbose_name='Категория неисправности'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='visit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визита инженера'),
        ),
    ]
