# Generated by Django 3.1.7 on 2021-03-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210323_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='ФИО инициатора заявки'),
        ),
    ]
