# Generated by Django 3.1.7 on 2021-03-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210324_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_time'], 'permissions': (('can_l_d_c_u', 'Может rec_list, rec_detail, rec_create и rec_update'), ('can_l_d', 'Может только rec_list и rec_detail'))},
        ),
    ]
