# Generated by Django 3.1.7 on 2021-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210324_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_time'], 'permissions': (('can_create_update', 'Может rec_create и rec_update'), ('can_list_detail', 'Может rec_list и rec_detail'))},
        ),
    ]
