# Generated by Django 3.1.7 on 2021-03-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210324_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.CharField(default='Принята', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
