# Generated by Django 3.1.7 on 2021-03-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210325_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='sign',
        ),
        migrations.AddField(
            model_name='rec',
            name='signd',
            field=models.DateField(null=True, verbose_name='Дата передачи заявки инженеру'),
        ),
        migrations.AddField(
            model_name='rec',
            name='signt',
            field=models.TimeField(null=True, verbose_name='Время передачи заявки инженеру'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='status',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.status', verbose_name='Статус заявки'),
        ),
    ]
