# Generated by Django 3.1.7 on 2021-03-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210323_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='sign',
            field=models.DateTimeField(blank=True, default=0.0005, verbose_name='Дата и время передачи заявки инженеру'),
            preserve_default=False,
        ),
    ]
