# Generated by Django 3.1.7 on 2021-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210325_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='visit',
        ),
        migrations.AddField(
            model_name='rec',
            name='visit_day_begin',
            field=models.DateField(null=True, verbose_name='Дата начала робот'),
        ),
        migrations.AddField(
            model_name='rec',
            name='visit_day_end',
            field=models.DateField(null=True, verbose_name='Дата окончания работ'),
        ),
        migrations.AddField(
            model_name='rec',
            name='visit_time_begin',
            field=models.DateField(null=True, verbose_name='Время начала робот'),
        ),
        migrations.AddField(
            model_name='rec',
            name='visit_time_end',
            field=models.DateField(null=True, verbose_name='Время окончания работ'),
        ),
    ]
