# Generated by Django 3.1.7 on 2021-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210327_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='visit_time_begin',
            field=models.TimeField(null=True, verbose_name='Время начала робот'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='visit_time_end',
            field=models.TimeField(null=True, verbose_name='Время окончания работ'),
        ),
    ]
