# Generated by Django 3.1.7 on 2021-03-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210327_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='signd',
            new_name='sign_day',
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='signt',
            new_name='sign_time',
        ),
    ]
