# Generated by Django 3.1.7 on 2021-03-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210327_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
