# Generated by Django 3.1.7 on 2021-03-28 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210328_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rec_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время создания заявки'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='sign_day',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 14, 30, 17, 780611), null=True, verbose_name='Дата передачи заявки инженеру'),
        ),
    ]
