# Generated by Django 3.1.7 on 2021-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210328_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='sign_day',
            field=models.DateField(null=True, verbose_name='Дата передачи заявки инженеру'),
        ),
    ]
