# Generated by Django 3.1.7 on 2021-03-29 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_auto_20210328_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Торговая сеть', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='rec',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер'),
        ),
        migrations.AddField(
            model_name='rec',
            name='retail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.retail', verbose_name='Торговая сеть'),
        ),
    ]
