# Generated by Django 3.1.7 on 2021-03-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210329_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='retail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.retail', verbose_name='Торговая сеть'),
        ),
    ]
