# Generated by Django 3.1.7 on 2021-03-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_store_retail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rec',
            options={'ordering': ['-rec_time'], 'permissions': (('can_create_update', 'Может rec_create и rec_update'), ('can_list_detail', 'Может rec_list и rec_detail')), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='retail',
            options={'verbose_name': 'Торговая сеть', 'verbose_name_plural': 'Торговые сети'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name': 'Инженер', 'verbose_name_plural': 'Инженеры'},
        ),
        migrations.AlterModelOptions(
            name='trouble',
            options={'verbose_name': 'Неисправность', 'verbose_name_plural': 'Неисправности'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='retail',
        ),
    ]
