# Generated by Django 3.1.7 on 2021-03-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210329_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rec_num',
            field=models.CharField(max_length=10, verbose_name='Номер заявки'),
        ),
    ]
