# Generated by Django 3.1.7 on 2021-03-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210330_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rec_num',
            field=models.CharField(max_length=8, verbose_name='Номер заявки'),
        ),
    ]
